# Generated by Django 3.1.2 on 2020-10-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_remove_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='image',
        ),
    ]
